# permissions for end users to edit indexerclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: indexercluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: splunk-upgrade-poc
    app.kubernetes.io/part-of: splunk-upgrade-poc
    app.kubernetes.io/managed-by: kustomize
  name: indexercluster-editor-role
rules:
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - indexerclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - indexerclusters/status
  verbs:
  - get
