---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - clustermanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - clustermanagers/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - clustermanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - indexerclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - indexerclusters/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - indexerclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - licensemanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - licensemanagers/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - licensemanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - monitoringconsoles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - monitoringconsoles/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - monitoringconsoles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - searchheadclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - searchheadclusters/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - searchheadclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - standalones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - standalones/finalizers
  verbs:
  - update
- apiGroups:
  - enterprise.splunk.poc
  resources:
  - standalones/status
  verbs:
  - get
  - patch
  - update
