apiVersion: enterprise.splunk.poc/v1
kind: Standalone
metadata:
  labels:
    app.kubernetes.io/name: standalone
    app.kubernetes.io/instance: standalone-sample
    app.kubernetes.io/part-of: splunk-upgrade-poc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: splunk-upgrade-poc
  name: standalone-sample
spec:
  image: registry.k8s.io/nginx-slim:0.8