apiVersion: enterprise.splunk.poc/v1
kind: SearchHeadCluster
metadata:
  labels:
    app.kubernetes.io/name: searchheadcluster
    app.kubernetes.io/instance: searchheadcluster-sample
    app.kubernetes.io/part-of: splunk-upgrade-poc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: splunk-upgrade-poc
  name: searchheadcluster-sample
spec:
  image: registry.k8s.io/nginx-slim:0.8
  clusterManagerRef:
    name: clustermanager-sample
  licenseManagerRef:
    name: licensemanager-sample